# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router_bridge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='router_bridge.proto',
  package='router_bridge',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13router_bridge.proto\x12\rrouter_bridge\"\x8e\x01\n\x0fProtocolMessage\x12:\n\x10interface_update\x18\x01 \x01(\x0b\x32\x1e.router_bridge.InterfaceUpdateH\x00\x12\x34\n\rrouter_packet\x18\x02 \x01(\x0b\x32\x1b.router_bridge.RouterPacketH\x00\x42\t\n\x07message\"?\n\x0fInterfaceUpdate\x12,\n\ninterfaces\x18\x01 \x03(\x0b\x32\x18.router_bridge.Interface\"2\n\tInterface\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\r\x12\x0b\n\x03mac\x18\x03 \x01(\x0c\"/\n\x0cRouterPacket\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x06proto3')
)




_PROTOCOLMESSAGE = _descriptor.Descriptor(
  name='ProtocolMessage',
  full_name='router_bridge.ProtocolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface_update', full_name='router_bridge.ProtocolMessage.interface_update', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='router_packet', full_name='router_bridge.ProtocolMessage.router_packet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='router_bridge.ProtocolMessage.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=39,
  serialized_end=181,
)


_INTERFACEUPDATE = _descriptor.Descriptor(
  name='InterfaceUpdate',
  full_name='router_bridge.InterfaceUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interfaces', full_name='router_bridge.InterfaceUpdate.interfaces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=246,
)


_INTERFACE = _descriptor.Descriptor(
  name='Interface',
  full_name='router_bridge.Interface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='router_bridge.Interface.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='router_bridge.Interface.ip', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='router_bridge.Interface.mac', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=298,
)


_ROUTERPACKET = _descriptor.Descriptor(
  name='RouterPacket',
  full_name='router_bridge.RouterPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='router_bridge.RouterPacket.interface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='router_bridge.RouterPacket.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=347,
)

_PROTOCOLMESSAGE.fields_by_name['interface_update'].message_type = _INTERFACEUPDATE
_PROTOCOLMESSAGE.fields_by_name['router_packet'].message_type = _ROUTERPACKET
_PROTOCOLMESSAGE.oneofs_by_name['message'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['interface_update'])
_PROTOCOLMESSAGE.fields_by_name['interface_update'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['message']
_PROTOCOLMESSAGE.oneofs_by_name['message'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['router_packet'])
_PROTOCOLMESSAGE.fields_by_name['router_packet'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['message']
_INTERFACEUPDATE.fields_by_name['interfaces'].message_type = _INTERFACE
DESCRIPTOR.message_types_by_name['ProtocolMessage'] = _PROTOCOLMESSAGE
DESCRIPTOR.message_types_by_name['InterfaceUpdate'] = _INTERFACEUPDATE
DESCRIPTOR.message_types_by_name['Interface'] = _INTERFACE
DESCRIPTOR.message_types_by_name['RouterPacket'] = _ROUTERPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtocolMessage = _reflection.GeneratedProtocolMessageType('ProtocolMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCOLMESSAGE,
  __module__ = 'router_bridge_pb2'
  # @@protoc_insertion_point(class_scope:router_bridge.ProtocolMessage)
  ))
_sym_db.RegisterMessage(ProtocolMessage)

InterfaceUpdate = _reflection.GeneratedProtocolMessageType('InterfaceUpdate', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACEUPDATE,
  __module__ = 'router_bridge_pb2'
  # @@protoc_insertion_point(class_scope:router_bridge.InterfaceUpdate)
  ))
_sym_db.RegisterMessage(InterfaceUpdate)

Interface = _reflection.GeneratedProtocolMessageType('Interface', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACE,
  __module__ = 'router_bridge_pb2'
  # @@protoc_insertion_point(class_scope:router_bridge.Interface)
  ))
_sym_db.RegisterMessage(Interface)

RouterPacket = _reflection.GeneratedProtocolMessageType('RouterPacket', (_message.Message,), dict(
  DESCRIPTOR = _ROUTERPACKET,
  __module__ = 'router_bridge_pb2'
  # @@protoc_insertion_point(class_scope:router_bridge.RouterPacket)
  ))
_sym_db.RegisterMessage(RouterPacket)


# @@protoc_insertion_point(module_scope)
